# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- garth-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed

# 3. Gem settings
paginate: 5 # jekyll-paginate > items per page
paginate_path: page:num # jekyll-paginate > blog page

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Asia/Seoul # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: 개발자의 기록  # 블로그 제목 변경
    output: true
    description: "개발 여정을 기록하는 공간입니다. 프로그래밍, 소프트웨어 아키텍처, 그리고 기술적 경험들을 공유합니다." # 블로그 설명 변경

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "개발자의 기록" # 사이트 이름 변경
logo: "/assets/logo.svg" # Site logo
favicon: "/favicon.ico" # 파비콘 활성화
description: "프로그래밍, 소프트웨어 개발, 그리고 기술적 경험들을 공유하는 개발 블로그입니다." # 사이트 설명 변경
url: "https://kensin8026.github.io" # 사이트 URL 변경
baseurl: ""
lang: ko-KR # 언어 설정 변경

# 8. 소셜 미디어 설정
social:
  github: "kensin8026"
  # 필요에 따라 다른 소셜 미디어 추가
  # twitter: "your_username"
  # linkedin: "your_username"

# 9. 저자 정보
author:
  name: "송재정"
  # email: "your.email@example.com" # 원하는 경우 이메일 추가